spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: duytc

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: false
    open-in-view: false

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      # Configure Main Scheduler Properties
      org.quartz.scheduler.instanceName: MyScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.instanceIdGenerator.class: com.example.quartzscheduler.config.CustomQuartzInstanceIdGenerator
      # Configure ThreadPool
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10
      org.quartz.threadPool.threadPriority: 5
      # Configure JobStore
      org.quartz.jobStore.misfireThreshold: 500
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.useProperties: true
      org.quartz.jobStore.dataSource: mysql
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.isClustered: false
      org.quartz.jobStore.clusterCheckinInterval: 15000
      # Configure Datasources
      org.quartz.dataSource.mysql.driver: com.mysql.cj.jdbc.Driver
      org.quartz.dataSource.mysql.URL: jdbc:mysql://localhost:3306/quartz-job
      org.quartz.dataSource.mysql.user: root
      org.quartz.dataSource.mysql.password: duytc
      org.quartz.dataSource.mysql.maxConnections: 5
      org.quartz.dataSource.mysql.validationQuery: select 0 from dual
    auto-startup: true
    wait-for-jobs-to-complete-on-shutdown: true



